gripper:
  #Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  #Effort Controllers
  # First
  mcp_first_joint_effort_controller:
    type: effort_controllers/JointPositionController
    joint: mcp_first_joint
    pid: {p: 10.0, i: 0.01, d: 3.0}

  dc_first_joint_effort_controller:
    type: effort_controllers/JointPositionController
    joint: dc_first_joint
    pid: {p: 10.0, i: 0.01, d: 3.0}

  # Second
  mcp_second_joint_effort_controller:
    type: effort_controllers/JointPositionController
    joint: mcp_second_joint
    pid: {p: 10.0, i: 0.01, d: 3.0}

  dc_second_joint_effort_controller:
    type: effort_controllers/JointPositionController
    joint: dc_second_joint
    pid: {p: 10.0, i: 0.01, d: 3.0}

  # Third
  mcp_third_joint_effort_controller:
    type: effort_controllers/JointPositionController
    joint: mcp_third_joint
    pid: {p: 10.0, i: 0.01, d: 3.0}

  dc_third_joint_effort_controller:
    type: effort_controllers/JointPositionController
    joint: dc_third_joint
    pid: {p: 10.0, i: 0.01, d: 3.0}

  # Fourth
  mcp_fourth_joint_effort_controller:
    type: effort_controllers/JointPositionController
    joint: mcp_fourth_joint
    pid: {p: 10.0, i: 0.01, d: 3.0}

  dc_fourth_joint_effort_controller:
    type: effort_controllers/JointPositionController
    joint: dc_fourth_joint
    pid: {p: 10.0, i: 0.01, d: 3.0}

